from __future__ import annotations

import os
import stat
import sys
import tempfile
import time
import types
import unittest
from pathlib import Path

# Keep the unit tests runnable before optional runtime dependencies are installed.
if "dotenv" not in sys.modules:
    dotenv = types.ModuleType("dotenv")
    dotenv.load_dotenv = lambda: None
    sys.modules["dotenv"] = dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ytbot"))

from config import Config  # noqa: E402
from core.auth import (  # noqa: E402
    OAuthTelegramLogger,
    active_cookie_path,
    configured_cookie_path,
    inspect_cookies_file,
    install_cookies_file,
    is_bot_detection_error,
    is_format_unavailable_error,
    is_hard_youtube_block,
    is_rate_limit_error,
    validate_cookies_file,
)
from core.state import FAILED, PENDING, StateManager, Task  # noqa: E402


def netscape_cookie(
    domain: str = ".youtube.com",
    name: str = "SAPISID",
    value: str = "test-secret",
    http_only: bool = False,
    expires: int | None = None,
) -> str:
    expires = expires or int(time.time()) + 86_400
    prefix = "#HttpOnly_" if http_only else ""
    return (
        "# Netscape HTTP Cookie File\n"
        "# generated by test\n\n"
        f"{prefix}{domain}\tTRUE\t/\tTRUE\t{expires}\t{name}\t{value}\n"
    )


class CookieValidationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.old_data_dir = Config.DATA_DIR
        self.old_base_dir = Config.BASE_DIR
        self.old_cookie_path = Config.COOKIES_PATH
        Config.DATA_DIR = self.root / "data"
        Config.BASE_DIR = self.root
        Config.COOKIES_PATH = ""

    def tearDown(self) -> None:
        Config.DATA_DIR = self.old_data_dir
        Config.BASE_DIR = self.old_base_dir
        Config.COOKIES_PATH = self.old_cookie_path
        self.tmp.cleanup()

    def write(self, name: str, content: str) -> Path:
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def test_valid_youtube_cookie_reports_safe_metadata(self) -> None:
        path = self.write("upload.txt", netscape_cookie())
        info, error = inspect_cookies_file(path)

        self.assertEqual(error, "")
        self.assertIsNotNone(info)
        self.assertEqual(info.cookie_count, 1)
        self.assertEqual(info.youtube_cookie_count, 1)
        self.assertEqual(info.auth_cookie_count, 1)
        self.assertTrue(info.has_login_cookies)

    def test_http_only_netscape_row_is_accepted(self) -> None:
        path = self.write("upload.txt", netscape_cookie(http_only=True, name="SID"))
        valid, error = validate_cookies_file(path)
        self.assertTrue(valid, error)

    def test_json_or_unrelated_cookie_export_is_rejected(self) -> None:
        json_path = self.write("cookies.txt", '[{"domain": ".youtube.com"}]')
        self.assertFalse(validate_cookies_file(json_path)[0])

        unrelated = self.write(
            "other.txt",
            netscape_cookie(domain=".example.com", name="SID"),
        )
        valid, error = validate_cookies_file(unrelated)
        self.assertFalse(valid)
        self.assertIn("youtube.com", error)

    def test_malformed_row_is_rejected_with_line_number(self) -> None:
        path = self.write(
            "bad.txt",
            "# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\tmissing-columns\n",
        )
        valid, error = validate_cookies_file(path)
        self.assertFalse(valid)
        self.assertIn("line `2`", error)

    def test_invalid_upload_never_overwrites_existing_file(self) -> None:
        destination = self.write("data/cookies.txt", netscape_cookie(value="keep-me"))
        original = destination.read_bytes()
        invalid = self.write("incoming.txt", "not a Netscape cookie export")

        with self.assertRaises(ValueError):
            install_cookies_file(invalid, destination)

        self.assertEqual(destination.read_bytes(), original)

    def test_install_is_atomic_and_detected_without_restart(self) -> None:
        incoming = self.write("incoming.txt", netscape_cookie(value="fresh"))
        destination = configured_cookie_path()
        info = install_cookies_file(incoming, destination)

        self.assertEqual(info.path, destination.resolve())
        self.assertFalse(incoming.exists())
        self.assertEqual(active_cookie_path(), destination.resolve())
        if os.name == "posix":
            self.assertEqual(stat.S_IMODE(destination.stat().st_mode), 0o600)

    def test_relative_custom_path_is_based_at_application_directory(self) -> None:
        Config.COOKIES_PATH = "private/youtube-cookies.txt"
        self.assertEqual(
            configured_cookie_path(),
            (self.root / "private/youtube-cookies.txt").resolve(),
        )


class YouTubeErrorClassificationTests(unittest.TestCase):
    def test_generic_format_error_does_not_pause_the_whole_queue(self) -> None:
        error = "Requested format is not available. Use --list-formats"
        self.assertTrue(is_format_unavailable_error(error))
        self.assertFalse(is_bot_detection_error(error))

    def test_429_and_only_images_are_auth_block_evidence(self) -> None:
        self.assertTrue(is_rate_limit_error("HTTP Error 429: Too Many Requests"))
        self.assertTrue(is_hard_youtube_block("HTTP Error 429: Too Many Requests"))
        self.assertTrue(is_bot_detection_error("HTTP Error 429: Too Many Requests"))
        self.assertTrue(is_hard_youtube_block("Only images are available for download"))
        self.assertTrue(is_bot_detection_error("Only images are available for download"))

    def test_yt_dlp_warning_context_is_retained(self) -> None:
        logger = OAuthTelegramLogger()
        logger.warning("Unable to download webpage: HTTP Error 429: Too Many Requests")
        logger.error("Requested format is not available")
        context = logger.diagnostic_context()
        self.assertIn("HTTP Error 429", context)
        self.assertIn("Requested format", context)


class AuthFailureRecoveryTests(unittest.TestCase):
    def test_only_matching_old_auth_failures_are_requeued(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            state = StateManager(Path(tmp) / "state.json")
            state.tasks = {
                "auth": Task(
                    id="auth",
                    url="https://youtu.be/aaaaaaaaaaa",
                    status=FAILED,
                    error="Bot detection: HTTP Error 429",
                ),
                "deleted": Task(
                    id="deleted",
                    url="https://youtu.be/bbbbbbbbbbb",
                    status=FAILED,
                    error="Video unavailable: uploader deleted this video",
                ),
            }
            recovered = state.retry_failed_matching(("bot detection", "http error 429"))
            self.assertEqual(recovered, 1)
            self.assertEqual(state.tasks["auth"].status, PENDING)
            self.assertEqual(state.tasks["deleted"].status, FAILED)


class RuntimePathTests(unittest.TestCase):
    def test_default_data_path_is_inside_ytbot_not_process_cwd(self) -> None:
        expected = (ROOT / "ytbot" / "data").resolve()
        self.assertEqual(Config.DATA_DIR, expected)


if __name__ == "__main__":
    unittest.main()
